title: OMGN
description: >
  The Oomycete Molecular Genetics Network (OMGN) is an international community
  dedicated to molecular genetics, functional genomics, and cell biology of oomycetes.

theme: minima
lang: en

url: "https://oomycetes.com"
baseurl: ""

collections:
  pages:
    output: true
    permalink: /:name/
