title: OMGN

description: >
  The Oomycete Molecular Genetics Network (OMGN) is an international scientific
  community dedicated to oomycete molecular genetics, genomics, cell biology,
  evolution, plant pathology, and the development of research tools and resources.

theme: minima
lang: en

url: "https://oomycetes.com"
baseurl: ""

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true

header_pages:
  - _pages/oomycetes.md
  - _pages/community.md
  - _pages/meetings.md
  - _pages/committee.md

permalink: /:name/
